In [1]:
from PIL import Image
import os
import matplotlib.pyplot as plt
from array import array
import numpy as np
import cv2
import sift

In [ ]:
import harris

In [ ]:
im = np.array(Image.open("/home/jaxa/toshiki/sfmtutorial/IMG20241217171723.jpg").convert("L"))
harrisim = harris.compute_harris_response(im)
filtered_coords = harris.get_harris_points(harrisim, 50)
harris.plot_harris_points(im, filtered_coords)

im = np.array(Image.open("/home/jaxa/toshiki/sfmtutorial/IMG20241217172928.jpg").convert("L"))
harrisim = harris.compute_harris_response(im)
filtered_coords = harris.get_harris_points(harrisim, 50)
harris.plot_harris_points(im, filtered_coords)

In [ ]:
im1 = np.array(Image.open("/home/jaxa/toshiki/sfmtutorial/IMG20241217172928.jpg").convert("L"))
im2 = np.array(Image.open("/home/jaxa/toshiki/sfmtutorial/IMG20241217172928.jpg").convert("L"))

wid = 5
harrisim = harris.compute_harris_response(im1, 5)
filtered_coords1 = harris.get_harris_points(harrisim, 50)
d1 = harris.get_descriptors(im1, filtered_coords1, wid)

harrisim = harris.compute_harris_response(im2, 5)
filtered_coords2 = harris.get_harris_points(harrisim, 50)
d2 = harris.get_descriptors(im2, filtered_coords2, wid)

print("start matching")
matches = harris.match_twosided(d1, d2)

plt.figure()
plt.gray()
harris.plot_matches(im1, im2, filtered_coords1, filtered_coords2, matches)
plt.show()

In [2]:
import sift

In [ ]:
image_path = "/home/jaxa/toshiki/sfmtutorial/scan9/00000014.jpg"

img, keypoints, descriptors = sift.feature_detection(image_path)
sift.plot_features(img, keypoints)

In [ ]:
img1, keys1, des1 = sift.feature_detection("/home/jaxa/toshiki/sfmtutorial/scan9/00000014.jpg")
img2, keys2, des2 = sift.feature_detection("/home/jaxa/toshiki/sfmtutorial/scan9/00000022.jpg")

print("start matching")
matches = sift.match_twosided(des1, des2)

plt.figure()
plt.gray()
harris.plot_matches(im1, im2, filtered_coords1, filtered_coords2, matches)
plt.show()

In [ ]:
imname = "/home/jaxa/toshiki/sfmtutorial/scan82/000014.png"
img = cv2.imread(imname, cv2.IMREAD_GRAYSCALE)
sift = cv2.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(img, None)
print(keypoints[0])
kp = keypoints[0]
print(f"座標: {kp.pt}")
print(f"スケール: {kp.size}")
print(f"方向: {kp.angle}")
print(f"応答値: {kp.response}")
print(f"ピラミッドレベル: {kp.octave}")
np.hstack((np.array(kp.pt), np.array(kp.size), np.array(kp.angle)))

In [ ]:
imname = "/home/jaxa/toshiki/sfmtutorial/scan9/00000014.jpg"
im1 = np.array(Image.open(imname).convert("L"))
sift.process_image(imname, "no14.sift")
l1, d1 = sift.read_features_from_file("no14.sift")

plt.figure()
plt.gray()
sift.plot_features(im1, l1, circle=True)
plt.show()

In [ ]:
img1 = "/home/jaxa/toshiki/sfmtutorial/scan9/00000014.jpg"
img1_gray = np.array(Image.open(img1).convert("L"))

print(img1_gray.shape)

plt.imshow(img1_gray, cmap='gray')
plt.axis("off")
plt.show()

In [ ]:
img1 = "/home/jaxa/toshiki/sfmtutorial/scan9/00000014.jpg"
img2 = "/home/jaxa/toshiki/sfmtutorial/scan9/00000022.jpg"



img1_gray = np.array(Image.open(img1).convert("L"))
img2_gray = np.array(Image.open(img2).convert("L"))


sift.process_image(img1, "no14.sift")
sift.process_image(img2, "no22.sift")

l1, d1 = sift.read_features_from_file("no14.sift")
l2, d2 = sift.read_features_from_file("no22.sift")


print("start matching")
matches = sift.match_twosided(d1, d2)

plt.figure()
plt.gray()
sift.plot_matches(img1_gray, img2_gray, l1, l2, matches)
plt.show()

In [2]:
import sift

In [ ]:
dir_path = "scan9"
output_path = "sift"

files = os.listdir(dir_path)
print(files)

sift.detect_multiview_features(dir_path, output_path)

In [ ]:
import pydot

g = pydot.Dot(graph_type="graph")

g.add_node(pydot.Node(str(0), fontcolor="transparent"))

for i in range(5):
    g.add_node(pydot.Node(str(i+1)))
    g.add_edge(pydot.Edge(str(0), str(i+1)))
    for i in range(5)

In [5]:
dir_path = "scan9_mini"
sift_path = "sift_mini"

matchscores =  sift.matching_multiview(dir_path, sift_path)
print(matchscores)

comparing  00000007.jpg   00000007.jpg
number of matches =  6177
comparing  00000007.jpg   00000025.jpg
number of matches =  13
comparing  00000007.jpg   00000028.jpg
number of matches =  190
comparing  00000007.jpg   00000016.jpg
number of matches =  9
comparing  00000007.jpg   00000012.jpg
number of matches =  8
comparing  00000007.jpg   00000000.jpg
number of matches =  137
comparing  00000007.jpg   00000021.jpg
number of matches =  1
comparing  00000007.jpg   00000003.jpg
number of matches =  0
comparing  00000025.jpg   00000025.jpg
number of matches =  4207
comparing  00000025.jpg   00000028.jpg
number of matches =  65
comparing  00000025.jpg   00000016.jpg
number of matches =  0
comparing  00000025.jpg   00000012.jpg
number of matches =  0
comparing  00000025.jpg   00000000.jpg
number of matches =  11
comparing  00000025.jpg   00000021.jpg
number of matches =  0
comparing  00000025.jpg   00000003.jpg
number of matches =  2
comparing  00000028.jpg   00000028.jpg
number of matches 

In [6]:
np.save("matchscores.npy", matchscores)

In [3]:
matchscores = np.load("matchscores_room.npy")
print(matchscores)

[[5.396e+03 4.000e+00 6.470e+02 2.140e+02 1.130e+03 6.120e+02 5.600e+01]
 [4.000e+00 2.067e+03 7.700e+01 1.000e+00 0.000e+00 1.000e+00 1.180e+02]
 [6.470e+02 7.700e+01 3.880e+03 1.100e+01 5.590e+02 3.230e+02 2.000e+02]
 [2.140e+02 1.000e+00 1.100e+01 7.319e+03 3.960e+02 1.026e+03 0.000e+00]
 [1.130e+03 0.000e+00 5.590e+02 3.960e+02 5.908e+03 1.078e+03 1.000e+01]
 [6.120e+02 1.000e+00 3.230e+02 1.026e+03 1.078e+03 6.389e+03 0.000e+00]
 [5.600e+01 1.180e+02 2.000e+02 0.000e+00 1.000e+01 0.000e+00 1.220e+03]]


In [5]:
import pydot

In [7]:
threshold = 2

images_path = "/home/jaxa/toshiki/sfmtutorial/room/room_resize"
output_path = "thumbnail"
files_images = os.listdir(images_path)
nbr_images = len(files_images)

g = pydot.Dot(graph_type="graph")
for i in range(nbr_images):
    for j in range(i+1, nbr_images):
        if matchscores[i, j] > threshold:
            im = Image.open(os.path.join(images_path, files_images[i]))
            im.thumbnail((100, 100))
            filename = files_images[i]
            im.save("thumbnail/"+filename)
            g.add_node(pydot.Node(str(i), fontcolor='transparent', shape="rectangle", image="/home/jaxa/toshiki/sfmtutorial/thumbnail/"+filename))

            im = Image.open(os.path.join(images_path, files_images[j]))
            im.thumbnail((100, 100))
            filename = files_images[j]

            im.save("thumbnail/"+filename)
            g.add_node(pydot.Node(str(j), fontcolor='transparent', shape="rectangle", image="/home/jaxa/toshiki/sfmtutorial/thumbnail/"+filename))

            g.add_edge(pydot.Edge(str(i), str(j)))

g.write_png("scenegraph_room.png")